In [1]:
import pandas as pd
import seaborn as sns
import numpy as np
import scipy.stats as stats

In [2]:
import seaborn as sns
dataset = sns.load_dataset('tips')

In [3]:
dataset

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

# Chi_Square Test

In [4]:
data = pd.crosstab(dataset['sex'],dataset['smoker'])
data

smoker  Yes  No
sex            
Male     60  97
Female   33  54

In [5]:
#Observed values
observed_value = data.values
observed_value

array([[60, 97],
       [33, 54]], dtype=int64)

In [6]:
val = stats.chi2_contingency(data)

In [7]:
val

(0.0,
 1.0,
 1,
 array([[59.84016393, 97.15983607],
        [33.15983607, 53.84016393]]))

In [8]:
expexted_value = val[3]

In [9]:
expexted_value

array([[59.84016393, 97.15983607],
       [33.15983607, 53.84016393]])

In [10]:
no_of_row = len(data.iloc[0:2,0])
no_of_columns = len(data.iloc[0,0:2])
ddof = (no_of_row-1)*(no_of_columns-1)
alpha = 0.05

In [11]:
from scipy.stats import chi2
chi_square = sum([(o-e)**2/e for o,e in zip(observed_value,expexted_value)])
chi_square

array([0.00119737, 0.00073745])

In [12]:
chi_test = chi_square[0]+chi_square[1]
print('Chi_Square statistic :', chi_test)

Chi_Square statistic : 0.001934818536627623


In [13]:
#p_value
p_value = 1-chi2.cdf(x=chi_square,df=ddof)
print("p_value" ,p_value[0])
print('signigicant level', alpha)

p_value 0.9723963138872089
signigicant level 0.05


In [14]:
if p_value[0]<= alpha :
    print('Reject H0')
else :
    print('Accept H0')

Accept H0


In [15]:
dataset2 = pd.get_dummies(dataset,drop_first=True) 

In [16]:
dataset2

total_bill   tip  size  sex_Female  smoker_No  day_Fri  day_Sat  day_Sun  \
0         16.99  1.01     2           1          1        0        0        1   
1         10.34  1.66     3           0          1        0        0        1   
2         21.01  3.50     3           0          1        0        0        1   
3         23.68  3.31     2           0          1        0        0        1   
4         24.59  3.61     4           1          1        0        0        1   
..          ...   ...   ...         ...        ...      ...      ...      ...   
239       29.03  5.92     3           0          1        0        1        0   
240       27.18  2.00     2           1          0        0        1        0   
241       22.67  2.00     2           0          0        0        1        0   
242       17.82  1.75     2           0          1        0        1        0   
243       18.78  3.00     2           1          1        0        0        0   

     time_Dinner  
0              1  
1              1  
2              1  
3              1  
4              1  
..           ...  
239            1  
240            1  
241            1  
242            1  
243            1  

[244 rows x 9 columns]

In [17]:
from sklearn.feature_selection import chi2

In [20]:
from sklearn.model_selection import train_test_split
X_train,X_test ,y_train,y_test = train_test_split(dataset2.iloc[:,1:],dataset2.iloc[:,:1],test_size=.25)

In [29]:
y_train=y_train.astype('int') #To fix a bug appear when I try to implement ch2 

In [21]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [24]:
model.score(X_test,y_test)

0.2857346579365365

In [26]:
model.score(X_train,y_train)

0.6409775229223587

In [ ]:
for col in dataset2:
    print(dataset2[col].unique)

In [44]:
f_score,p_value = chi2(X_train,y_train)

In [45]:
f_score

array([81.06471212, 34.95738274, 22.28015545, 17.54118577, 37.46363636,
       21.25851795, 25.07924439,  9.20596312])

In [46]:
p_value

array([1.61895656e-05, 4.70226402e-01, 9.53008517e-01, 9.93935621e-01,
       3.56751221e-01, 9.67347324e-01, 8.92353287e-01, 9.99996448e-01])

In [47]:
p_value = pd.Series(p_value)
p_value.index = X_train.columns
p_value

tip            0.000016
size           0.470226
sex_Female     0.953009
smoker_No      0.993936
day_Fri        0.356751
day_Sat        0.967347
day_Sun        0.892353
time_Dinner    0.999996
dtype: float64

In [48]:
p_value.sort_index(ascending=False)

tip            0.000016
time_Dinner    0.999996
smoker_No      0.993936
size           0.470226
sex_Female     0.953009
day_Sun        0.892353
day_Sat        0.967347
day_Fri        0.356751
dtype: float64

In [54]:
from sklearn.model_selection import train_test_split
X_train2,X_test2 ,y_train2,y_test2 = train_test_split(dataset2.iloc[:,1:5],dataset2.iloc[:,:1],test_size=.25)

In [55]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train2,y_train2)

LinearRegression()

In [57]:
model.score(X_test2,y_test2)

0.6785781710604277

In [58]:
model.score(X_train2,y_train2)

0.5215245073681695